# Generated by Django 2.2.2 on 2019-09-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcodex_bible', '0001_initial'),
        ('dcodex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('period', models.CharField(choices=[('E', 'Easter'), ('P', 'Pentecost'), ('F', 'Feast of the Cross'), ('L', 'Lent'), ('G', 'Great Week')], max_length=1)),
                ('week', models.CharField(max_length=15)),
                ('weekday_number', models.CharField(max_length=32)),
                ('earliest_date', models.CharField(max_length=15)),
                ('latest_date', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Days of year',
            },
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=16)),
                ('passage_description', models.CharField(max_length=32)),
                ('day_of_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.DayOfYear')),
            ],
        ),
        migrations.CreateModel(
            name='LectionaryVerse',
            fields=[
                ('verse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex.Verse')),
                ('bible_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_bible.BibleVerse')),
                ('lection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.Lection')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex.verse',),
        ),
        migrations.CreateModel(
            name='LectionVerseSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_verse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LectionVerseSpan_end_verse', to='dcodex_lectionary.LectionaryVerse')),
                ('lection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.Lection')),
                ('start_verse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LectionVerseSpan_start_verse', to='dcodex_lectionary.LectionaryVerse')),
            ],
        ),
    ]
