# Generated by Django 2.2.2 on 2019-09-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0004_auto_20190921_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectioninsystem',
            old_name='fixed_day',
            new_name='fixed_date',
        ),
    ]
