# Generated by Django 2.2.2 on 2020-01-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0007_lectioninsystem_cumulative_mass_lections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectioninsystem',
            options={'ordering': ['order', 'fixed_date', 'day_of_year', 'order_on_day']},
        ),
        migrations.AddField(
            model_name='dayofyear',
            name='description',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
