# Generated by Django 2.2.2 on 2020-02-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0011_auto_20200225_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectioninsystem',
            name='day_of_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.DayOfYear'),
        ),
        migrations.AlterField(
            model_name='lectioninsystem',
            name='fixed_date',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.FixedDate'),
        ),
    ]
