# Generated by Django 2.2.2 on 2020-03-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0013_auto_20200302_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectioninsystem',
            name='occasion_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='occasion_text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='reference_membership',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.LectionInSystem'),
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='reference_text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lectioninsystem',
            name='lection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.Lection'),
        ),
    ]
