# Generated by Django 2.2.2 on 2020-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0019_auto_20200316_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lection',
            name='verses',
        ),
    ]
