# Generated by Django 3.0.8 on 2020-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0025_affiliationlections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationlections',
            name='lections',
            field=models.ManyToManyField(blank=True, help_text='All the lections at which this affiliation object is active.', to='dcodex_lectionary.Lection'),
        ),
    ]
