# Generated by Django 3.0.8 on 2020-08-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0025_auto_20200809_1536'),
        ('dcodex_lectionary', '0026_auto_20200809_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationLectionarySystem',
            fields=[
                ('affiliationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex.AffiliationBase')),
                ('exclude', models.ManyToManyField(blank=True, help_text='All the lections at which this affiliation object is not active.', to='dcodex_lectionary.Lection')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.LectionarySystem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex.affiliationbase',),
        ),
    ]
