# Generated by Django 3.0.6 on 2020-08-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0027_affiliationlectionarysystem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliationlectionarysystem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='affiliationlections',
            options={},
        ),
    ]
