# Generated by Django 2.2.2 on 2019-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0002_remove_lectionaryverse_unique_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionaryverse',
            name='unique_string',
            field=models.CharField(default='', max_length=20),
        ),
    ]
