# Generated by Django 2.2.2 on 2019-09-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0003_lectionaryverse_unique_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lectioninsystem',
            name='day_of_year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.DayOfYear'),
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='fixed_day',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.FixedDate'),
        ),
    ]
