# Generated by Django 2.2.2 on 2019-09-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0005_auto_20190921_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectioninsystem',
            options={'ordering': ['fixed_date', 'day_of_year', 'order_on_day']},
        ),
    ]
