# Generated by Django 2.2.2 on 2019-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0006_auto_20190927_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectioninsystem',
            name='cumulative_mass_lections',
            field=models.IntegerField(default=-1),
        ),
    ]
