# Generated by Django 2.2.2 on 2020-02-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0009_fixeddate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lection',
            options={'ordering': ['first_bible_verse_id', 'description']},
        ),
        migrations.AddField(
            model_name='lection',
            name='first_bible_verse_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lection',
            name='first_verse_id',
            field=models.IntegerField(default=0),
        ),
    ]
