# Generated by Django 2.2.2 on 2020-02-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0010_auto_20200221_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectioninsystem',
            options={'ordering': ('order', 'fixed_date', 'day_of_year', 'order_on_day')},
        ),
    ]
