# Generated by Django 2.2.2 on 2020-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0012_auto_20200225_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixeddate',
            options={'ordering': ('date', 'description')},
        ),
        migrations.AlterField(
            model_name='fixeddate',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
