# Generated by Django 2.2.2 on 2020-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0014_auto_20200314_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectioninsystem',
            name='incipit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
