# Generated by Django 2.2.2 on 2020-03-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0015_lectioninsystem_incipit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectionaryverse',
            name='bible_verse',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dcodex_bible.BibleVerse'),
        ),
        migrations.AlterField(
            model_name='lectionaryverse',
            name='unique_string',
            field=models.CharField(default='', max_length=100),
        ),
    ]
