# Generated by Django 2.2.2 on 2020-03-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0017_auto_20200314_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectionaryverse',
            options={'ordering': ('bible_verse',)},
        ),
        migrations.CreateModel(
            name='LectionaryVerseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('lection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.Lection')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.LectionaryVerse')),
            ],
            options={
                'ordering': ['order', 'verse__bible_verse'],
            },
        ),
    ]
