# Generated by Django 2.2.2 on 2020-03-16 07:49

from django.db import migrations

# https://stackoverflow.com/questions/26927705/django-migration-error-you-cannot-alter-to-or-from-m2m-fields-or-add-or-remove/51351406

def create_through_relations(apps, schema_editor):
    Lection = apps.get_model('dcodex_lectionary', 'Lection')
    LectionaryVerseMembership = apps.get_model('dcodex_lectionary', 'LectionaryVerseMembership')
    for lection in Lection.objects.all():
        for verse in lection.verses.all():
            LectionaryVerseMembership(
                verse=verse,
                lection=lection
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0018_auto_20200316_1848'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),    
    ]
