# Generated by Django 2.2.2 on 2020-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0020_remove_lection_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='verses',
            field=models.ManyToManyField(through='dcodex_lectionary.LectionaryVerseMembership', to='dcodex_lectionary.LectionaryVerse'),
        ),
    ]
