# Generated by Django 2.2.2 on 2020-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0021_lection_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionaryverse',
            name='mass',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
