# Generated by Django 2.2.2 on 2020-05-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0022_lectionaryverse_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectionaryversemembership',
            name='cummulative_mass_from_lection_start',
            field=models.IntegerField(default=0, help_text='The total mass of verses from the beginning of the lection until this verse'),
        ),
        migrations.AlterField(
            model_name='dayofyear',
            name='period',
            field=models.CharField(choices=[('E', 'Easter'), ('P', 'Pentecost'), ('F', 'Feast of the Cross'), ('L', 'Lent'), ('G', 'Great Week'), ('T', 'Epiphany')], max_length=1),
        ),
    ]
