# Generated by Django 2.2.2 on 2020-05-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0020_affiliationbase_name'),
        ('dcodex_lectionary', '0024_auto_20200526_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationLections',
            fields=[
                ('affiliationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex.AffiliationBase')),
                ('lections', models.ManyToManyField(help_text='All the lections at which this affiliation object is active.', to='dcodex_lectionary.Lection')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex.affiliationbase',),
        ),
    ]
