# Generated by Django 3.0.11 on 2020-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0028_auto_20200813_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofyear',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dayofyear',
            name='week',
            field=models.CharField(max_length=31),
        ),
    ]
