# Generated by Django 3.0.11 on 2020-11-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcodex_lectionary', '0029_auto_20201116_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectionaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dcodex_lectionary.lectionaryday_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EothinaDay',
            fields=[
                ('lectionaryday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex_lectionary.LectionaryDay')),
                ('rank', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex_lectionary.lectionaryday',),
        ),
        migrations.CreateModel(
            name='FixedDay',
            fields=[
                ('lectionaryday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex_lectionary.LectionaryDay')),
                ('date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
            bases=('dcodex_lectionary.lectionaryday',),
        ),
        migrations.CreateModel(
            name='MiscDay',
            fields=[
                ('lectionaryday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex_lectionary.LectionaryDay')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex_lectionary.lectionaryday',),
        ),
        migrations.CreateModel(
            name='MovableDay',
            fields=[
                ('lectionaryday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex_lectionary.LectionaryDay')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('period', models.CharField(choices=[('E', 'Easter'), ('P', 'Pentecost'), ('F', 'Feast of the Cross'), ('L', 'Lent'), ('G', 'Great Week'), ('T', 'Epiphany')], max_length=1)),
                ('week', models.CharField(max_length=31)),
                ('weekday_number', models.CharField(max_length=32)),
                ('earliest_date', models.CharField(max_length=15)),
                ('latest_date', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex_lectionary.lectionaryday',),
        ),
        migrations.AddField(
            model_name='lectioninsystem',
            name='lectionary_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_lectionary.LectionaryDay'),
        ),
    ]
