# Generated by Django 3.0.11 on 2020-11-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0030_auto_20201119_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movableday',
            old_name='period',
            new_name='season',
        ),
    ]
