# Generated by Django 3.0.11 on 2020-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0031_auto_20201119_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eothinaday',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterModelOptions(
            name='miscday',
            options={'ordering': ('description',)},
        ),
        migrations.AlterModelOptions(
            name='movableday',
            options={'ordering': ('rank', 'id')},
        ),
        migrations.RemoveField(
            model_name='lectionaryday',
            name='description',
        ),
        migrations.AddField(
            model_name='miscday',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movableday',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
