# Generated by Django 3.0.11 on 2020-11-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0032_auto_20201119_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectioninsystem',
            old_name='lectionary_day',
            new_name='day',
        ),
    ]
