# Generated by Django 3.0.11 on 2020-11-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0033_auto_20201119_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectioninsystem',
            options={'ordering': ('order', 'day', 'order_on_day')},
        ),
    ]
