# Generated by Django 3.2.6 on 2021-08-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_lectionary', '0034_auto_20201122_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movableday',
            name='earliest_date',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='movableday',
            name='latest_date',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='movableday',
            name='week',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='movableday',
            name='weekday_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
